name: cosmos
base: core22
version: '1.0'
summary: Infinite terminal universe
description: |
  Animated procedural universe in terminal.

grade: stable
confinement: strict

apps:
  cosmos:
    command: cosmos

parts:
  cosmos:
    plugin: dump
    source: .
